FROM node:18-alpine

WORKDIR /app

# We only need the minimal setup. 
# NPM will use the anonymous volume for node_modules.
COPY package*.json ./

RUN npm install

# In dev, we don't COPY . . because the volume handles it, 
# but we keep it for image completeness.
COPY . .

ENV HOST=0.0.0.0
ENV PORT=4321

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4321"]